node_js:
    - "lts/*"
    - "12"
    - "10"
php:
    - 7.4
    - 8.0
    - nightly
dist: bionic
stages:
    - "PHP lint tests"
    - "Backoffice assets tests"
branches:
    except:
        - l10n_develop

jobs:
    allow_failures:
        -   php: nightly

    include:
        -   stage: "Backoffice assets tests"
            language: node_js
            node_js: "lts/*"
            script: sh .travis/backoffice_assets.sh
        -   stage: "Backoffice assets tests"
            language: node_js
            node_js: "12"
            script: sh .travis/backoffice_assets.sh
        -   stage: "Backoffice assets tests"
            language: node_js
            node_js: "10"
            script: sh .travis/backoffice_assets.sh

        -   stage: "PHP lint tests"
            language: php
            sudo: required
            services:
                - mysql
            env:
                - DB=mysql
                - MYSQL_VERSION=5.7
                - MYSQL_PASSWORD=
            php: 7.4
            install: sh .travis/composer_install.sh
            script: sh .travis/php_lint.sh
        -   stage: "PHP lint tests"
            language: php
            sudo: required
            services:
                - mysql
            env:
                - DB=mysql
                - MYSQL_VERSION=5.7
                - MYSQL_PASSWORD=
            php: 8.0
            install: sh .travis/composer_install.sh
            script: sh .travis/php_lint.sh
        -   stage: "PHP lint tests"
            language: php
            sudo: required
            services:
                - mysql
            env:
                - DB=mysql
                - MYSQL_VERSION=5.7
                - MYSQL_PASSWORD=
            php: nightly
            install: sh .travis/composer_install.sh
            script: sh .travis/php_lint.sh



